"""
Deployment node (Phase 9).

Pauses for a lightweight (code-free) approval, then assembles a deployment
package under artifacts/<thread_id>/: a runnable starter `pipeline.py` stitched
from the approved preprocessing + feature-engineering code, a `requirements.txt`,
and a reference to the persisted model.
"""

from typing import Any, Dict, Optional

from workflows.state import GraphState
from utils.hitl import request_review
from utils.logging_utils import create_log
from utils.artifacts import get_artifacts_dir

REQUIREMENTS = "\n".join(
    [
        "pandas",
        "numpy",
        "scikit-learn",
        "scipy",
        "joblib",
    ]
)


def _build_pipeline_script(state: GraphState) -> str:
    target = state.get("target_column") or "target"
    best_model = state.get("best_model") or {}
    feature_columns = best_model.get("feature_columns") or []

    preprocessing = state.get("preprocessing_code") or "# (no preprocessing step)"
    feature_eng = state.get("feature_engineering_code") or "# (no feature engineering step)"

    return f'''"""
Auto-generated by DataPilot AI — STARTER inference pipeline.

This stitches together the approved preprocessing and feature-engineering steps
and loads the trained model. Review it before using in production: the steps
were generated for analysis and may assume the target column is present.

Usage:  python pipeline.py path/to/new_data.csv

Writes "<input>_predictions.csv" next to the input: the original input rows with
a "prediction" column appended.
"""
import sys
import pandas as pd
import numpy as np
import joblib

CSV_PATH = sys.argv[1] if len(sys.argv) > 1 else "data.csv"
OUTPUT_PATH = CSV_PATH.rsplit(".", 1)[0] + "_predictions.csv"
TARGET = {target!r}
FEATURE_COLUMNS = {feature_columns!r}

df = pd.read_csv(CSV_PATH)
original_df = df.copy()   # keep the raw inputs to save alongside predictions
outputs = {{}}

# === Preprocessing ===
{preprocessing}

# === Feature Engineering ===
{feature_eng}

# === Inference ===
model = joblib.load("model.pkl")
if FEATURE_COLUMNS and all(col in df.columns for col in FEATURE_COLUMNS):
    X = df[FEATURE_COLUMNS]
else:
    X = df.drop(columns=[c for c in [TARGET] if c in df.columns])

predictions = model.predict(X)

# Save inputs + predictions (prediction as the last column).
result = original_df.copy()
if len(predictions) == len(result):
    result["prediction"] = predictions
else:
    # Preprocessing changed the row count; align by index where possible.
    result = result.join(pd.Series(predictions, index=X.index, name="prediction"))

result.to_csv(OUTPUT_PATH, index=False)
print(f"Saved {{len(result)}} rows with predictions to {{OUTPUT_PATH}}")
'''


def deployment_node(state: GraphState, config=None) -> Dict[str, Any]:
    step = "deployment_node"
    logs = [create_log(step=step, message="Preparing deployment artifacts")]

    best_model = state.get("best_model") or {}
    proposed = ["pipeline.py", "requirements.txt"]
    if best_model.get("path"):
        proposed.append("model.pkl")

    review_event = create_log(step=step, message="Awaiting deployment approval")
    logs.append(review_event)

    # Code-free (plan-style) review: just confirm artifact generation.
    request_review(
        phase="deployment",
        title="Generate deployment package",
        message="Approve to generate the deployment artifacts listed below.",
        code=None,
        explanation="Will generate: " + ", ".join(proposed),
        logs=[review_event],
        proposed_artifacts=proposed,
    )

    run_dir = get_artifacts_dir(config)

    script_path = run_dir / "pipeline.py"
    script_path.write_text(_build_pipeline_script(state), encoding="utf-8")

    req_path = run_dir / "requirements.txt"
    req_path.write_text(REQUIREMENTS, encoding="utf-8")

    artifacts = [
        {"name": "pipeline.py", "path": str(script_path), "type": "script"},
        {"name": "requirements.txt", "path": str(req_path), "type": "requirements"},
    ]
    if best_model.get("path"):
        artifacts.append(
            {"name": "model.pkl", "path": best_model["path"], "type": "model"}
        )

    logs.append(create_log(step=step, message="Generated deployment artifacts"))

    return {
        "deployment_artifacts": artifacts,
        "event_logs": [create_log(step=step, message="Completed deployment")],
        "execution_logs": logs,
    }
